// PM JSON → Typst source string.
//
// proto-b/findings.md confirmed Typst is the print PDF backend; this
// module is the Phase 1 implementation of "PM tree → Typst source".
//
// We produce a self-contained .typ document with:
//   - `set text(lang: ..., font: ...)` from typography font tokens
//   - `set par(...)` for academic body line height
//   - heading / equation / citation / figure markup native to Typst
//
// Citations get rendered as `[Label]` plain text in Phase 1; bibliography
// integration via Typst `bibliography()` is Phase 2 once we materialise
// the Citation table to a `.bib` / Hayagriva file at export time.

// PmNode / PmMark / PmDocInput live in @collaborationtool/schema (Phase 1.5
// extraction per ADR-0005 §2.4) and are re-exported from this package's
// index for ergonomic consumers.

import type { PmDocInput, PmMark, PmNode } from '@collaborationtool/schema';
import {
  applyCjkSpacing,
  fontTokensToTypst,
  getFontTokens,
  smartQuoteByLang,
  type LanguageTag,
} from '@collaborationtool/typography';

import { escapeTypstMarkup, escapeTypstString } from './escape';

export type { PmDocInput, PmMark, PmNode };

export interface TypstSourceOptions {
  primaryLanguage: LanguageTag;
  title: string;
  /** Page size string for Typst `set page(paper: ...)`. Default 'a4'. */
  paper?: string;
  /** Body font size with unit, e.g. "11pt". Default 11pt. */
  fontSize?: string;
}

export function pmToTypstSource(
  pmDoc: PmDocInput,
  options: TypstSourceOptions,
): string {
  if (pmDoc.type !== 'doc') {
    throw new Error(
      `pmToTypstSource: expected root type 'doc', got '${pmDoc.type}'`,
    );
  }

  const fonts = getFontTokens(options.primaryLanguage);
  const langForTypst = options.primaryLanguage.split('-')[0]!; // 'zh' / 'en'
  const region = options.primaryLanguage.includes('-')
    ? options.primaryLanguage.split('-')[1]!.toLowerCase()
    : undefined;

  const preamble = [
    `// Generated by @collaborationtool/render-typst`,
    `#set document(title: "${escapeTypstString(options.title)}")`,
    `#set page(paper: "${options.paper ?? 'a4'}", margin: 2cm)`,
    region
      ? `#set text(lang: "${langForTypst}", region: "${region}", font: ${fontTokensToTypst(fonts.serif)}, size: ${options.fontSize ?? '11pt'})`
      : `#set text(lang: "${langForTypst}", font: ${fontTokensToTypst(fonts.serif)}, size: ${options.fontSize ?? '11pt'})`,
    `#set par(leading: 0.7em, justify: true)`,
    `#show heading: set text(font: ${fontTokensToTypst(fonts.serif)})`,
    `#show raw: set text(font: ${fontTokensToTypst(fonts.mono)})`,
    '',
    `= ${escapeTypstMarkup(applyTypographyPrePass(options.title, options.primaryLanguage))}`,
    '',
  ].join('\n');

  const body = ((pmDoc.content ?? []) as PmNode[])
    .map((b) => renderBlock(b, options))
    .join('\n\n');

  return `${preamble}\n${body}\n`;
}

function renderBlock(node: PmNode, opts: TypstSourceOptions): string {
  switch (node.type) {
    case 'paragraph':
      return renderInlineRun(node.content, opts);
    case 'heading': {
      const depth = clampDepth(Number(node.attrs?.['level'] ?? 1));
      const prefix = '='.repeat(depth);
      return `${prefix} ${renderInlineRun(node.content, opts).trim()}`;
    }
    case 'equation': {
      const latex = String(node.attrs?.['latex'] ?? '');
      // Typst native math doesn't accept LaTeX directly. Phase 1 wraps
      // the LaTeX as a typst raw block annotated for downstream
      // processing (Phase 2 wires `latex2typst` or invokes mitex).
      return `#align(center, raw("${escapeTypstString(latex)}", lang: "latex", block: true))`;
    }
    case 'computational-cell':
    case 'computationalCell': {
      const lang = String(node.attrs?.['kernel'] ?? 'python');
      const source = String(node.attrs?.['sourceCode'] ?? '');
      return '```' + lang + '\n' + source + '\n```';
    }
    case 'figure': {
      const src = String(node.attrs?.['src'] ?? '');
      const captionNode = (node.content ?? []).find(
        (c) => c.type === 'figureCaption' || c.type === 'figure-caption',
      );
      const caption = captionNode
        ? renderInlineRun(captionNode.content, opts)
        : '';
      const captionTypst = caption
        ? `\n  caption: [${caption}],`
        : '';
      return `#figure(\n  image("${escapeTypstString(src)}"),${captionTypst}\n)`;
    }
    case 'blockquote': {
      const inner = (node.content ?? [])
        .map((c) => renderBlock(c, opts))
        .join('\n');
      return `#quote(block: true)[\n${inner}\n]`;
    }
    case 'list': {
      return (node.content ?? [])
        .map((li) => `- ${renderInlineRun(li.content, opts)}`)
        .join('\n');
    }
    default:
      return renderInlineRun(node.content, opts);
  }
}

function renderInlineRun(
  content: PmNode[] | undefined,
  opts: TypstSourceOptions,
): string {
  if (!content) return '';
  return content.map((n) => renderInlineNode(n, opts)).join('');
}

function renderInlineNode(node: PmNode, opts: TypstSourceOptions): string {
  switch (node.type) {
    case 'text': {
      const value = applyTypographyPrePass(node.text ?? '', opts.primaryLanguage);
      let out = escapeTypstMarkup(value);
      const marks = node.marks ?? [];
      if (marks.some((m) => m.type === 'italic')) out = `_${out}_`;
      if (marks.some((m) => m.type === 'bold')) out = `*${out}*`;
      const anchor = marks.find(
        (m) => m.type === 'annotationAnchor' || m.type === 'annotation-anchor',
      );
      if (anchor) {
        out = `#highlight[${out}]`;
      }
      return out;
    }
    case 'inlineEquation':
    case 'inline-equation': {
      const latex = String(node.attrs?.['latex'] ?? '');
      // Phase 1: emit the LaTeX as inline raw with lang=latex; Phase 2
      // converts to Typst's native $...$ math via mitex.
      return ` #raw("${escapeTypstString(latex)}", lang: "latex") `;
    }
    case 'citationRef':
    case 'citation-ref': {
      const id = String(node.attrs?.['citationId'] ?? '');
      const label = String(node.attrs?.['label'] ?? id.slice(0, 8));
      return `[${escapeTypstMarkup(label)}]`;
    }
    case 'datasetRef':
    case 'dataset-ref': {
      const label = String(node.attrs?.['label'] ?? 'dataset');
      return `[${escapeTypstMarkup(label)}]`;
    }
    case 'footnoteRef':
    case 'footnote-ref': {
      const label = String(node.attrs?.['label'] ?? '*');
      return `#footnote[${escapeTypstMarkup(label)}]`;
    }
    default:
      return '';
  }
}

function applyTypographyPrePass(
  text: string,
  primaryLanguage: LanguageTag,
): string {
  return smartQuoteByLang(applyCjkSpacing(text), {
    primaryLanguage,
  });
}

function clampDepth(n: number): number {
  if (n <= 1) return 1;
  if (n >= 6) return 6;
  return n;
}
