// Stress test for the Yjs CRDT layer beneath proto-a's editor schema.
//
// Goal: verify that `n` simulated clients running random concurrent
// operations against the same Y.Doc topology converge to byte-identical
// XmlFragment state. This isolates the CRDT-merge concern from
// ProseMirror's schema-recovery behavior; the latter is left to manual
// dual-tab tests in the browser (see findings.md).
//
// What this DOES catch:
//   - CRDT divergence (clients ending in different states)
//   - Atom-node id collisions (we generate uuidv7 per insert)
//   - State-vector inconsistency
//
// What this DOES NOT catch:
//   - ProseMirror schema validity (no PM here; just Y.Xml*)
//   - y-prosemirror "schema recovery" warnings (browser only)
//   - Annotation-mark anchor-tracking edge cases (PM-level)
//
// Run: pnpm proto-a:stress

import * as Y from 'yjs';
import { v7 as uuidv7 } from 'uuid';

interface ClientState {
  id: number;
  doc: Y.Doc;
  pendingUpdates: Uint8Array[];
}

const NUM_CLIENTS = 5;
const OPS_PER_CLIENT = 50;
const SEED_BASE = 42;

// Tiny seeded RNG so runs are reproducible.
function mulberry32(seed: number): () => number {
  let s = seed >>> 0;
  return () => {
    s = (s + 0x6d2b79f5) >>> 0;
    let t = s;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

type Op =
  | { kind: 'insertParagraph'; text: string }
  | { kind: 'insertHeading'; level: number; text: string }
  | { kind: 'insertCitationAtom'; citationId: string; label: string }
  | { kind: 'insertEquationAtom'; latex: string }
  | { kind: 'insertCellAtom'; cellId: string }
  | { kind: 'deleteFirstChild' }
  | { kind: 'appendTextToLastParagraph'; text: string };

function randomOp(rng: () => number, clientId: number): Op {
  const r = rng();
  if (r < 0.25) {
    return {
      kind: 'insertParagraph',
      text: `c${clientId}-p-${uuidv7().slice(0, 8)}`,
    };
  } else if (r < 0.4) {
    return {
      kind: 'insertHeading',
      level: 2,
      text: `c${clientId}-h-${uuidv7().slice(0, 6)}`,
    };
  } else if (r < 0.55) {
    return {
      kind: 'insertCitationAtom',
      citationId: uuidv7(),
      label: `cite-${clientId}`,
    };
  } else if (r < 0.7) {
    return {
      kind: 'insertEquationAtom',
      latex: `x_{${clientId}} = ${Math.floor(r * 1000)}`,
    };
  } else if (r < 0.8) {
    return { kind: 'insertCellAtom', cellId: uuidv7() };
  } else if (r < 0.9 && rng() < 0.5) {
    return { kind: 'deleteFirstChild' };
  }
  return {
    kind: 'appendTextToLastParagraph',
    text: ` t${clientId}-${uuidv7().slice(0, 5)}`,
  };
}

function applyOp(client: ClientState, op: Op): void {
  const fragment = client.doc.getXmlFragment('body');
  client.doc.transact(() => {
    switch (op.kind) {
      case 'insertParagraph': {
        const p = new Y.XmlElement('paragraph');
        p.insert(0, [new Y.XmlText(op.text)]);
        fragment.insert(fragment.length, [p]);
        break;
      }
      case 'insertHeading': {
        const h = new Y.XmlElement('heading');
        h.setAttribute('level', String(op.level));
        h.insert(0, [new Y.XmlText(op.text)]);
        fragment.insert(fragment.length, [h]);
        break;
      }
      case 'insertCitationAtom': {
        const ref = new Y.XmlElement('citationRef');
        ref.setAttribute('blockId', uuidv7());
        ref.setAttribute('citationId', op.citationId);
        ref.setAttribute('label', op.label);
        // Atom nodes are leaves; no children.
        let lastP: Y.XmlElement | null = null;
        for (let i = fragment.length - 1; i >= 0; i--) {
          const n = fragment.get(i);
          if (n instanceof Y.XmlElement && n.nodeName === 'paragraph') {
            lastP = n;
            break;
          }
        }
        if (lastP) {
          lastP.insert(lastP.length, [ref]);
        } else {
          const p = new Y.XmlElement('paragraph');
          p.insert(0, [ref]);
          fragment.insert(fragment.length, [p]);
        }
        break;
      }
      case 'insertEquationAtom': {
        const eq = new Y.XmlElement('equation');
        eq.setAttribute('blockId', uuidv7());
        eq.setAttribute('latex', op.latex);
        fragment.insert(fragment.length, [eq]);
        break;
      }
      case 'insertCellAtom': {
        const cell = new Y.XmlElement('computationalCell');
        cell.setAttribute('blockId', uuidv7());
        cell.setAttribute('cellId', op.cellId);
        cell.setAttribute('kernel', 'molab');
        cell.setAttribute('sourceCode', `# generated by stress\nprint(${op.cellId.slice(0, 4)!.length})`);
        fragment.insert(fragment.length, [cell]);
        break;
      }
      case 'deleteFirstChild': {
        if (fragment.length > 0) {
          fragment.delete(0, 1);
        }
        break;
      }
      case 'appendTextToLastParagraph': {
        let lastP: Y.XmlElement | null = null;
        for (let i = fragment.length - 1; i >= 0; i--) {
          const n = fragment.get(i);
          if (n instanceof Y.XmlElement && n.nodeName === 'paragraph') {
            lastP = n;
            break;
          }
        }
        if (lastP) {
          lastP.insert(lastP.length, [new Y.XmlText(op.text)]);
        } else {
          const p = new Y.XmlElement('paragraph');
          p.insert(0, [new Y.XmlText(op.text)]);
          fragment.insert(fragment.length, [p]);
        }
        break;
      }
    }
  });
}

function broadcast(clients: ClientState[], from: ClientState, update: Uint8Array): void {
  for (const c of clients) {
    if (c.id === from.id) continue;
    Y.applyUpdate(c.doc, update);
  }
}

function fragmentSnapshot(c: ClientState): string {
  return JSON.stringify(c.doc.getXmlFragment('body').toJSON());
}

async function runStress(): Promise<void> {
  const clients: ClientState[] = [];
  for (let i = 0; i < NUM_CLIENTS; i++) {
    const doc = new Y.Doc();
    const pending: Uint8Array[] = [];
    doc.on('update', (update: Uint8Array, origin: unknown) => {
      // Capture only local-origin updates to broadcast
      if (origin !== 'remote') pending.push(update);
    });
    clients.push({ id: i, doc, pendingUpdates: pending });
  }

  // Round-robin operations with broadcast after each op (simulating
  // real-time but unordered network delivery; we randomise order below).
  const allOps: { clientIdx: number; op: Op }[] = [];
  for (let i = 0; i < NUM_CLIENTS; i++) {
    const rng = mulberry32(SEED_BASE + i);
    for (let j = 0; j < OPS_PER_CLIENT; j++) {
      allOps.push({ clientIdx: i, op: randomOp(rng, i) });
    }
  }
  // Shuffle ops to interleave clients.
  const shuffleRng = mulberry32(SEED_BASE * 7919);
  for (let i = allOps.length - 1; i > 0; i--) {
    const j = Math.floor(shuffleRng() * (i + 1));
    [allOps[i], allOps[j]] = [allOps[j]!, allOps[i]!];
  }

  let warningCount = 0;
  const originalWarn = console.warn;
  console.warn = (...args: unknown[]) => {
    warningCount++;
    originalWarn('[captured]', ...args);
  };

  // Apply each op locally and propagate the resulting update.
  for (const entry of allOps) {
    const c = clients[entry.clientIdx]!;
    applyOp(c, entry.op);
    while (c.pendingUpdates.length > 0) {
      const update = c.pendingUpdates.shift()!;
      broadcast(clients, c, update);
    }
  }

  // Drain any straggling updates (should be none, since broadcast is sync).
  for (const c of clients) {
    while (c.pendingUpdates.length > 0) {
      const update = c.pendingUpdates.shift()!;
      broadcast(clients, c, update);
    }
  }

  console.warn = originalWarn;

  // Verify convergence: all clients' XmlFragment serialise to the
  // same JSON.
  const snapshots = clients.map(fragmentSnapshot);
  const ref = snapshots[0]!;
  let allEqual = true;
  for (let i = 1; i < snapshots.length; i++) {
    if (snapshots[i] !== ref) {
      allEqual = false;
      console.error(`[FAIL] Client ${i} diverged from client 0.`);
      console.error('Client 0 length:', ref.length, 'snapshot start:', ref.slice(0, 200));
      console.error(`Client ${i} length:`, snapshots[i]!.length, 'snapshot start:', snapshots[i]!.slice(0, 200));
    }
  }

  // Verify state vectors agree.
  const stateVectorsHex = clients.map((c) =>
    Buffer.from(Y.encodeStateVector(c.doc)).toString('hex')
  );
  const svRef = stateVectorsHex[0]!;
  let svEqual = true;
  for (let i = 1; i < stateVectorsHex.length; i++) {
    if (stateVectorsHex[i] !== svRef) {
      svEqual = false;
      console.error(`[FAIL] Client ${i} state vector differs from client 0.`);
    }
  }

  // Output report.
  console.log('--- proto-a stress test report ---');
  console.log(`Clients          : ${NUM_CLIENTS}`);
  console.log(`Ops per client   : ${OPS_PER_CLIENT}`);
  console.log(`Total ops        : ${NUM_CLIENTS * OPS_PER_CLIENT}`);
  console.log(`Convergence      : ${allEqual ? 'PASS' : 'FAIL'}`);
  console.log(`State vectors    : ${svEqual ? 'PASS' : 'FAIL'}`);
  console.log(`Yjs warnings     : ${warningCount}`);
  console.log(`Final body size  : ${ref.length} chars (JSON)`);

  if (!allEqual || !svEqual) {
    process.exitCode = 1;
  }
}

runStress().catch((err) => {
  console.error('Stress test threw:', err);
  process.exit(2);
});
